pipeline {
  agent any

  environment {
    TELEGRAM_TOKEN = credentials('telegram-bot-token')
    CHAT_ID = "-1002115020059"
  }

  stages {
    stage("core_lib_build") {
      steps {
        echo "Start build core lib"
        dir ('src'){
          sh 'make build/core_lib.a'
        }
      }
    }

    stage("core_test") {
      steps {
        echo "Start build core test"
        dir('src') {
          sh 'make core_test'
        }
      }
    }
  }

  post {
    success {
      script {
        sh 'curl -s -X POST https://api.telegram.org/botcredentials('telegram-bot-token')/sendMessage -d chat_id=${CHAT_ID} -d text="success"'
      }
    }
    failure {
      script {
        sh 'curl -s -X POST https://api.telegram.org/bot7077729755:AAG5ZomuHtAH2YDhQxGeQlWtI4peKQuAmkg/sendMessage -d chat_id=-1002115020059 -d text="failure"'
      }
    }
  }
}
